"""add reminder_sent column in appointment

Revision ID: 49ebf955dc59
Revises: 8c642ea37bf3
Create Date: 2026-07-13 13:10:57.751627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ebf955dc59'
down_revision: Union[str, Sequence[str], None] = '8c642ea37bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "appointments",
    sa.Column(
        "reminder_sent",
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("false")
    )
)
    op.drop_index(op.f('idx_doctor_schedule'), table_name='appointments', postgresql_include=['appointment_date', 'appointment_time', 'status'])
    op.drop_index(op.f('index_appointments_doctor_date_time'), table_name='appointments')
    op.drop_index(op.f('index_appointments_doctor_status'), table_name='appointments')
    op.drop_index(op.f('index_appointments_patient_date_time'), table_name='appointments')
    op.drop_index(op.f('index_appointments_patient_status'), table_name='appointments')
    op.drop_index(op.f('index_custom_doctor_date'), table_name='customavailability')
    op.drop_index(op.f('index_doctor_specialisation'), table_name='doctor_profiles')
    op.drop_index(op.f('index_doctor_specialisation_city'), table_name='doctor_profiles')
    op.drop_index(op.f('index_medical_record_doctor_created'), table_name='medical_record')
    op.drop_index(op.f('index_medical_record_patient_created'), table_name='medical_record')
    op.drop_index(op.f('index_prescription_doctor_created'), table_name='prescription')
    op.drop_index(op.f('index_prescription_patient_created'), table_name='prescription')
    op.drop_index(op.f('index_recurring_day_of_week'), table_name='recurringavailability')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('index_recurring_day_of_week'), 'recurringavailability', ['doctor_id', 'day_of_week'], unique=False)
    op.create_index(op.f('index_prescription_patient_created'), 'prescription', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('index_prescription_doctor_created'), 'prescription', ['doctor_id', 'created_at'], unique=False)
    op.create_index(op.f('index_medical_record_patient_created'), 'medical_record', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('index_medical_record_doctor_created'), 'medical_record', ['doctor_id', 'created_at'], unique=False)
    op.create_index(op.f('index_doctor_specialisation_city'), 'doctor_profiles', ['specialisation', 'city'], unique=False)
    op.create_index(op.f('index_doctor_specialisation'), 'doctor_profiles', ['specialisation'], unique=False)
    op.create_index(op.f('index_custom_doctor_date'), 'customavailability', ['doctor_id', 'date'], unique=False)
    op.create_index(op.f('index_appointments_patient_status'), 'appointments', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('index_appointments_patient_date_time'), 'appointments', ['patient_id', 'appointment_date', 'appointment_time'], unique=False)
    op.create_index(op.f('index_appointments_doctor_status'), 'appointments', ['doctor_id', 'status'], unique=False)
    op.create_index(op.f('index_appointments_doctor_date_time'), 'appointments', ['doctor_id', 'appointment_date', 'appointment_time'], unique=False)
    op.create_index(op.f('idx_doctor_schedule'), 'appointments', ['doctor_id'], unique=False, postgresql_include=['appointment_date', 'appointment_time', 'status'])
    op.drop_column('appointments', 'reminder_sent')
    # ### end Alembic commands ###
